=== leandrodax/nfe310/src/main/java/br/gov/sp/fazenda/dsge/report/resources/reports_1_0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
Este é o DTD do arquivo de configuração do Reports 1.0.
Todos os arquivos de configuração reports.xml devem incluir um 
DOCTYPE da seguinte forma:

  <!DOCTYPE reports PUBLIC
	"-//Prodesp//DTD Reports 1.0//EN"
	"reports_1_0.dtd">
-->

<!--Elemento root que contém todos os elementos para configuração dos relatórios.-->
<!ELEMENT reports (report-location,datasource-param-suffix?,subreport-param-suffix?,report-parameter*,report*)>
<!--Elemento que define individualmente as configurações de cada relatório.-->
<!ELEMENT report (report-class?,report-datasource?,report-pageprovider?,report-data,subreport*,request-attributes?,saving-name?)>

<!--Atribuito que define o nome do relatório. Este nome deve ser o mesmo do arquivo compilado ".jasper".-->

<!--Atribuito que define se o relatório irá usar paginação na obtenção dos dados. O valor default para este atributo é "false", sem paginação. Os possíveis valores são: "true" ou "yes" e "false" ou "no".-->
<!ATTLIST report
name CDATA #REQUIRED
paging CDATA #IMPLIED
>
<!--Elemento que define qual a localização dos arquivos dos relatórios compilados.-->
<!ELEMENT report-location (#PCDATA)*>
<!--Elemento que define qual deve ser o sufixo dos parametros utilizados para identificarem os datasources os subrelatórios.-->
<!ELEMENT datasource-param-suffix (#PCDATA)*>
<!--Elemento que define qual deve ser o sufixo dos parametros utilizados para identificarem os subrelatórios.-->
<!ELEMENT subreport-param-suffix (#PCDATA)*>
<!--Elemento que define individualmente as configurações de cada subrelatório que este relatório contém.-->
<!ELEMENT subreport (subreport-datasource?,subreport-pageprovider?,subreport-data?,master-attribute?)>
<!--Elemento que define os atributos que serao passados para o report data via request -->
<!ELEMENT request-attributes (attribute-name*)>
<!--Elemento que define o atributo de nome de arquivo que sera gerado o relatorio -->
<!ELEMENT saving-name (#PCDATA)*>

<!--Atribuito que define o nome do subrelatório. Este nome deve ser o mesmo do arquivo compilado ".jasper".-->
<!--Atribuito que define se o subrelatório irá usar paginação na obtenção dos dados. O valor default para este atributo é "false", sem paginação. Os possíveis valores são: "true" ou "yes" e "false" ou "no".-->
<!--Atribuito que define se o subrelatório irá usar os mesmos dados do relatorio pai para ser populado -->
<!ATTLIST subreport
name CDATA #REQUIRED
paging CDATA #IMPLIED
master CDATA #IMPLIED
>
<!--Elemento que define qual a classe de relatório que será utilizada. O valor default para este elemento é a classe com.brq.report.GenericReport.-->
<!ELEMENT report-class (#PCDATA)*>
<!--Elemento que define qual a classe que implementa a interface com.brq.report.datasource.ReportDataSource que será utilizada. O valor default para este elemento é a classe com.brq.report.datasource.ValueObjectDataSource.-->
<!ELEMENT report-datasource (#PCDATA)*>
<!--Elemento que define qual a classe que implementa a interface com.brq.report.datasource.PageProvider que será utilizada. O valor default para este elemento é a classe com.brq.report.datasource.GenericPageProvider.-->
<!ELEMENT report-pageprovider (#PCDATA)*>
<!--Elemento que define qual a classe que será utilizada para obtenção dos dados. Deve ser informado o nome de uma classe que implemente a interface com.brq.report.datasource.ReportData.-->
<!ELEMENT report-data (#PCDATA)*>
<!--Elemento que define qual a classe que implementa a interface com.brq.report.datasource.PageProvider que será utilizada. O valor default para este elemento é a classe com.brq.report.datasource.GenericPageProvider.-->
<!ELEMENT subreport-pageprovider (#PCDATA)*>
<!--Elemento que define qual a classe que implementa a interface com.brq.report.datasource.ReportDataSource que será utilizada. O valor default para este elemento é a classe com.brq.report.datasource.ValueObjectDataSource.-->
<!ELEMENT subreport-datasource (#PCDATA)*>
<!--Elemento que define qual a classe que será utilizada para obtenção dos dados. Deve ser informado o nome de uma classe que implemente a interface com.brq.report.datasource.ReportData.-->
<!ELEMENT subreport-data (#PCDATA)*>
<!--Elemento que define um parametro para ser usado pelos relatórios.-->
<!ELEMENT report-parameter (parameter-name,parameter-value)>
<!--Elemento que define o nome do parametro.-->
<!ELEMENT parameter-name (#PCDATA)*>
<!--Elemento que define o valor do parametro.-->
<!ELEMENT parameter-value (#PCDATA)*>
<!--Elemento que define o nome do atributo na request -->
<!ELEMENT attribute-name (#PCDATA)*>
<!--Elemento que define qual o tipo da classe de ligacao entre o relatorio master e slave -->
<!ELEMENT master-attribute (name,class)>
<!--Elemento que define nome de atributo dentro da classe master para relacionamento com slave -->
<!ELEMENT name (#PCDATA)*>
<!--Elemento que define tipo da classe do atributo master para relacionameno com slave -->
<!ELEMENT class (#PCDATA)*>

=== leandrodax/nfe310/target/classes/br/gov/sp/fazenda/dsen/report/config/reports.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--  <!DOCTYPE reports PUBLIC "-//Prodesp//DTD Reports 1.0//EN" "/br/gov/sp/fazenda/dsge/report/resources/reports_1_0.dtd"> -->

<reports>
	<report-location>/br/gov/sp/fazenda/dsen/report</report-location>
	<datasource-param-suffix>_datasource</datasource-param-suffix>
	<subreport-param-suffix>_subreport</subreport-param-suffix>

	<!-- ========== -->
	<!-- Parametros -->
	<!-- ========== -->
	<report-parameter>
		<parameter-name>BRASAO</parameter-name>
		<parameter-value>br/gov/sp/fazenda/dsen/report/brasao.gif</parameter-value>
	</report-parameter>

	<!-- ============================= -->
	<!-- DANFE - orientação retrato A4 -->
	<!-- ============================= -->
    <report name="ImpressaoDanfeRetratoA4Report">
		<report-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeRD</report-data>
		<subreport name="ImpressaoDanfeItemRetratoA4Report">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeItemRD</subreport-data>
		</subreport>
		<subreport name="ImpressaoDanfeInfComplRetratoA4Report">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeInfComplRD</subreport-data>
		</subreport>
	</report>

	<!-- ============================== -->
	<!-- DANFE - orientação paisagem A4 -->
	<!-- ============================== -->    
    <report name="ImpressaoDanfePaisagemA4Report">
		<report-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeRD</report-data>
		<subreport name="ImpressaoDanfeItemPaisagemA4Report">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeItemRD</subreport-data>
		</subreport>
		<subreport name="ImpressaoDanfeInfComplPaisagemA4Report">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeInfComplRD</subreport-data>
		</subreport>
	</report>
	
	<!-- =================================== -->
	<!-- DANFE - orientação retrato Oficio 2 -->
	<!-- =================================== -->
    <report name="ImpressaoDanfeRetratoOFICIO2Report">
		<report-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeRD</report-data>
		<subreport name="ImpressaoDanfeItemRetratoOFICIO2Report">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeItemRD</subreport-data>
		</subreport>
		<subreport name="ImpressaoDanfeInfComplRetratoOFICIO2Report">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeInfComplRD</subreport-data>
		</subreport>
	</report>

	<!-- ==================================== -->
	<!-- DANFE - orientação paisagem Oficio 2 -->
	<!-- ==================================== -->    
    <report name="ImpressaoDanfePaisagemOFICIO2Report">
		<report-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeRD</report-data>
		<subreport name="ImpressaoDanfeItemPaisagemOFICIO2Report">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeItemRD</subreport-data>
		</subreport>
		<subreport name="ImpressaoDanfeInfComplPaisagemOFICIO2Report">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.ImpressaoDanfeInfComplRD</subreport-data>
		</subreport>
	</report>

   	<!-- =================== -->
	<!-- Relatorio Gerencial -->
	<!-- =================== -->
	<report name="RelatorioGerencialRetratoReport">
		<report-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialRD</report-data>
        <subreport name="RelatorioGerencialAutorizadasReport">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialDetalheRD</subreport-data>
		</subreport>
		<subreport name="RelatorioGerencialCanceladasReport">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialDetalheRD</subreport-data>
		</subreport>
		<subreport name="RelatorioGerencialDenegadasReport">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialDetalheRD</subreport-data>
		</subreport>
		<subreport name="RelatorioGerencialRejeitadasReport">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialDetalheRD</subreport-data>
		</subreport>
		<subreport name="RelatorioGerencialEmProcessamentoReport">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialDetalheRD</subreport-data>
		</subreport>
		<subreport name="RelatorioGerencialProblemaTransmissaoReport">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialDetalheRD</subreport-data>
		</subreport>
		<subreport name="RelatorioGerencialValidadaReport">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialDetalheRD</subreport-data>
		</subreport>
		<subreport name="RelatorioGerencialAssinadaReport">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialDetalheRD</subreport-data>
		</subreport>
		<subreport name="RelatorioGerencialEmDigitacaoReport">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialDetalheRD</subreport-data>
		</subreport>
		<subreport name="RelatorioGerencialInutilizadaReport">
			<subreport-data>br.gov.sp.fazenda.dsen.reportdata.RelatorioGerencialDetalheRD</subreport-data>
		</subreport>
	</report>
	    	
</reports>
